# AI Configuration

AI_PROVIDER = "gemini"

AI_MODEL = "gemini-3.6-flash"

PROMPT_VERSION = "v3"

MAX_STORIES = 100

MAX_ANALYSIS_PER_RUN=3

# Daily Scheduler
SCHEDULER_ENABLED = True
SCHEDULER_TIME = "07:00"
SCHEDULER_TIMEZONE = "Europe/Rome"
SCHEDULER_CHECK_SECONDS = 30
SCHEDULER_CATCH_UP = True